version: 2
updates:
  # Monitora le GitHub Actions (actions/checkout, setup-qemu, setup-buildx, login, build-push, delete-package-versions, dockerhub-description)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"

  # Monitora le immagini base Alpine nel Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "docker"
      include: "scope"
